### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by ryandanthony** [RockSolidKnowledge/Samples.IdentityServer4.AdminUiIntegration#2]
Hi All, 
Hopefully this is the right place to ask this question, please let me know if there is a better place to ask it. 

I am trying to setup the database prior to deploying for AdminUI + API via docker (likely). I have a separate  IdentityServer. 

I want to create a separate console app or assembly (and use `dotnet ef`) to create the database and do migrations.

In the mean time, I am trying to do it through my website for now:

```
serviceScope.ServiceProvider.GetRequiredService<IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext>().Database.Migrate();
serviceScope.ServiceProvider.GetRequiredService<IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext>().Database.Migrate();
serviceScope.ServiceProvider.GetRequiredService<IdentityExpress.Identity.IdentityExpressDbContext>().Database.Migrate();
```

But it doesn't create three of the tables that are used by AdminUI:
```
ExtendedClients
ExtendedIdentityResources
ExtendedApiResources
```

How do I create those?

Thanks,
Ryan

**Comment by scottbrady91** [comment]
Hi Ryan, these tables are automatically created by AdminUI on first run of the API half of the project. We do not support a way for you to manually run these migrations.

For support queries such as these, please email them directly to support@identityserver.com
