### ISSUE TITLE
How to create seed admin accoun?

### ISSUE THREAD

**Issue by codematrix** [RockSolidKnowledge/Samples.IdentityServer4.AdminUiIntegration#4]
Hi Team,

I manage to get the Database Migrated. Is there a way to create a seed Admin account? I managed to create an account and log in but it keeps complaining that I don't have any applications to manage.

Any help on this would be great.

Ross

**Comment by scottbrady91** [comment]
Hi, sorry about the delay in responding.

You'll want to ensure your account has the `AdminUI Administrator` role
