### ISSUE TITLE
No database schema created

### ISSUE THREAD

**Issue by mattwhetton** [RockSolidKnowledge/Samples.IdentityServer4.AdminUiIntegration#5]
Hi,

I think this might be my misunderstanding of what this project is meant to do, but I've built and ran it, but can see no database tables being created.

Am I meant to do something to get the schema created in the database? 
Is this project not for creating a sample admin ui?

If you could point me in the direction of anything that would be great.

Matt

**Comment by scottbrady91** [comment]
Hi! We use this project as our identity provider when demoing AdminUI. As a result, we leave AdminUI in charge of creating tables and seed data.

**Comment by JimBobSquarePants** [comment]
So this isn't for public consumption?

**Comment by scottbrady91** [comment]
It's a sample that is not intended for use in production.
