### ISSUE TITLE
AdminUI API Swagger not executing the values

### ISSUE THREAD

**Issue by SonalJadhav24** [RockSolidKnowledge/Samples.IdentityServer4.AdminUiIntegration#7]
Dear All,

I am working on AdminUI API, I have configured and run entity framework migrations on my identity server database. However when I try to access AdminUI API swagger UI , I cannot get the values from Get API listed on page (for users, claims, clients etcs.)

Could you please give me some pointers to resolve this ?

Thanks

Sonal

**Comment by scottbrady91** [comment]
Hi Sonal, to clarify: you can access the Swagger endpoint, and AdminUI is working, but you cannot use the Swagger UI? If so, you should be receiving a 401 when using the Swagger test tool.

We will be adding OAuth support in the next version so that you can automatically get tokens for testing with the Swagger UI.

**Comment by SonalJadhav24** [comment]
Thanks,
Scott the information. 

Yes, I cannot use Swagger UI, it gives me 401 unauthenticated error, if tested independently.
If, I go to  access Admin UI , then it fails to get all values from AdminUI API with NULL value and gives me all CORS error to receive data from API.


Could you help me with this ?

Sonal

**Comment by scottbrady91** [comment]
Okay, the API sounds like it's working then. In case you were interested, we'll be using an approach like the following to get authorization working for Swagger: https://www.scottbrady91.com/Identity-Server/ASPNET-Core-Swagger-UI-Authorization-using-IdentityServer4

For the CORS error, this sounds like a configuration issue. Could you send details and a screenshot of the error to support@identityserver.com?
